GET http://localhost:4004/odata/v4/catalog/Books?
###
GET http://localhost:4004/odata/v4/catalog/Authors
###
GET http://localhost:4004/odata/v4/catalog/Orders?
###
POST http://localhost:4004/odata/v4/catalog/Authors
Content-Type: application/json

{
    "ID": 101,
    "name": "47823"
}
###
POST http://localhost:4004/odata/v4/catalog/Orders
Content-Type: application/json;IEEE754Compatible=true

{
    "book_ID": 202,
    "amount": 1
}
###
PUT http://localhost:4004/odata/v4/catalog/submitOrder
Content-Type: application/json;IEEE754Compatible=true

{
    "book_ID": 202,
    "amount": 1,
    "status": "closed"
}
###
POST http://localhost:4004/odata/v4/catalog/Books
Content-Type: application/json

{
    "ID": 202,
    "title": "Test books 2",
    "author_ID": 101,
    "stock": 10,
    "genre_ID": 4,
    "prices": 12.5
}
###
PUT http://localhost:4004/odata/v4/catalog/Books(202)
Content-Type: application/json

{
    "ID": 202,
    "title": "Test books 2",
    "author_ID": 101,
    "stock": 9
}
###
DELETE http://localhost:4004/odata/v4/catalog/BooksComplete(202)
###
GET http://localhost:4004/odata/v4/catalog/BooksComplete
###
PUT http://localhost:4004/odata/v4/catalog/Orders(7428b5db-9c2c-430d-bd30-e50c80388f0c)
Content-Type: application/json

{
    "book_ID": 202,
    "amount": 7
}
###
DELETE http://localhost:4004/odata/v4/catalog/Orders(7428b5db-9c2c-430d-bd30-e50c80388f0c)
