GET http://localhost:4004/odata/v4/catalog/Books?
###
GET http://localhost:4004/odata/v4/catalog/Authors
###
GET http://localhost:4004/odata/v4/catalog/Orders?
###
POST http://localhost:4004/odata/v4/catalog/Authors
Content-Type: application/json

{
    "ID": 101,
    "name": "47823"
}
###
POST http://localhost:4004/odata/v4/catalog/Orders
Content-Type: application/json;IEEE754Compatible=true

{
    "book_ID": 202,
    "amount": 1
}
###
POST http://localhost:4004/odata/v4/catalog/Books
Content-Type: application/json

{
    "ID": 202,
    "title": "Test books 2",
    "author_ID": 101,
    "stock": 10,
    "genre_ID": 4,
    "prices": 12.5
}
###
PUT http://localhost:4004/odata/v4/catalog/Books(202)
Content-Type: application/json

{
    "ID": 202,
    "title": "Test books 2",
    "author_ID": 101,
    "stock": 9
}
###
DELETE http://localhost:4004/odata/v4/catalog/BooksComplete(202)
###
GET http://localhost:4004/odata/v4/catalog/BooksComplete
###
PUT http://localhost:4004/odata/v4/catalog/Orders(00462623-2f80-412c-aa26-701c19a513f4)
Content-Type: application/json

{
    "ID": "00462623-2f80-412c-aa26-701c19a513f4",
    "book_ID": 202,
    "amount": 7
}
###
DELETE http://localhost:4004/odata/v4/catalog/Orders(00462623-2f80-412c-aa26-701c19a513f4)
